// Generated by CoffeeScript 1.11.1
(function() {
  var doTest, numbo, testAmount, testAmountResult, testCheque, testChequeResult, testNum, testNumResult;

  numbo = require('./../lib/numbo.js');

  numbo.zhCN = require('./../lib/numbo.zhCN.js');

  testNum = require('./testNum.zhCN.js');

  testAmount = require('./testAmount.zhCN.js');

  testCheque = require('./testCheque.zhCN.js');

  doTest = function(testObj, option, job) {
    var expect, i, input, item, len, obj, output, result, results, summary;
    console.log("-------\nStart Test Job: " + job + "\n-------");
    results = (function() {
      var i, len, results1;
      results1 = [];
      for (i = 0, len = testObj.length; i < len; i++) {
        obj = testObj[i];
        input = obj['input'];
        output = numbo.zhCN(input, option);
        expect = obj['expect'];
        result = output === expect;
        console.log("[" + result + "]: Input of " + input + " returns \"" + output + "\", expected \"" + obj['expect'] + "\"");
        results1.push(result);
      }
      return results1;
    })();
    summary = {
      job: job,
      total: results.length,
      success: 0,
      fail: 0,
      report: ''
    };
    for (i = 0, len = results.length; i < len; i++) {
      item = results[i];
      if (item === false) {
        summary.fail++;
      } else if (item === true) {
        summary.success++;
      }
    }
    summary.report = job + " Test Results: " + summary.total + " tests, " + summary.success + " success, " + summary.fail + " fail";
    console.log("\n-------\n" + summary.report + "\n-------\n");
    return summary;
  };

  testNumResult = doTest(testNum, 'number', 'Converting Number');

  testAmountResult = doTest(testAmount, 'amount', 'Converting Amount');

  testChequeResult = doTest(testCheque, 'cheque', 'Converting Cheque');

  console.log("\n=======\nTest Summary in test.zhCN.js:\n" + testNumResult.report + "\n" + testAmountResult.report + "\n" + testChequeResult.report + "\n=======");

  console.log("\n=== test.js Test Done ===\n");

}).call(this);
