// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = [
    {
      'input': 0,
      'expect': '零'
    }, {
      'input': 1,
      'expect': '一'
    }, {
      'input': 2,
      'expect': '二'
    }, {
      'input': 9,
      'expect': '九'
    }, {
      'input': 10,
      'expect': '十'
    }, {
      'input': 11,
      'expect': '十一'
    }, {
      'input': 19,
      'expect': '十九'
    }, {
      'input': 20,
      'expect': '二十'
    }, {
      'input': 21,
      'expect': '二十一'
    }, {
      'input': 88,
      'expect': '八十八'
    }, {
      'input': 100,
      'expect': '一百'
    }, {
      'input': 101,
      'expect': '一百零一'
    }, {
      'input': 180,
      'expect': '一百八十'
    }, {
      'input': 888,
      'expect': '八百八十八'
    }, {
      'input': 1000,
      'expect': '一千'
    }, {
      'input': 1001,
      'expect': '一千零一'
    }, {
      'input': 1010,
      'expect': '一千零一十'
    }, {
      'input': '0000000',
      'expect': '零'
    }
  ];

}).call(this);
