// Generated by CoffeeScript 1.11.1
(function() {
  var doTest, i, j, jobDesc, k, lang, langs, len, len1, len2, numbo, result, results, testData, tpl, tpls;

  langs = ['enUS', 'zhCN', 'zhTW'];

  tpls = ['number', 'amount', 'cheque'];

  numbo = require('./../lib/numbo.js');

  numbo.zhTW = require('./../lib/numbo.zhTW.js');

  numbo.zhCN = require('./../lib/numbo.zhCN.js');

  testData = {
    enUS: {
      number: require('./testNum.js'),
      amount: require('./testAmount.js'),
      cheque: require('./testCheque.js')
    },
    zhCN: {
      number: require('./testNum.zhCN.js'),
      amount: require('./testAmount.zhCN.js'),
      cheque: require('./testCheque.zhCN.js')
    },
    zhTW: {
      number: require('./testNum.zhTW.js'),
      amount: require('./testAmount.zhTW.js'),
      cheque: require('./testCheque.zhTW.js')
    }
  };

  doTest = function(testObj, lang, option, job) {
    var expect, i, input, item, len, obj, output, result, results, summary;
    console.log("-> numbo.convert(input, " + lang + ", " + option + "):");
    results = (function() {
      var i, len, results1;
      results1 = [];
      for (i = 0, len = testObj.length; i < len; i++) {
        obj = testObj[i];
        input = obj['input'];
        output = numbo[lang](input, option);
        expect = obj['expect'];
        result = output === expect;
        results1.push(result);
      }
      return results1;
    })();
    summary = {
      job: job,
      total: results.length,
      success: 0,
      fail: 0,
      report: ''
    };
    for (i = 0, len = results.length; i < len; i++) {
      item = results[i];
      if (item === false) {
        summary.fail++;
      } else if (item === true) {
        summary.success++;
      }
    }
    summary.report = job + ": " + summary.total + " tests, " + summary.success + " success, " + summary.fail + " fail";
    console.log("Result: " + summary.total + " tests, " + summary.success + " success, " + summary.fail + " fail\n");
    return summary;
  };

  console.log("Starting Test\n=============\n\nError logs (that MAY not make the test fail):\n");

  results = [];

  for (i = 0, len = langs.length; i < len; i++) {
    lang = langs[i];
    for (j = 0, len1 = tpls.length; j < len1; j++) {
      tpl = tpls[j];
      jobDesc = "numbo.convert(input, '" + lang + "', '" + tpl + "')";
      result = doTest(testData[lang][tpl], lang, tpl, jobDesc);
      results.push(result);
    }
  }

  console.log("Summary\n=======\n");

  for (k = 0, len2 = results.length; k < len2; k++) {
    result = results[k];
    console.log(result.report);
  }

  console.log("\n=== Test Done ===\n");

}).call(this);
