// Generated by CoffeeScript 1.11.1

/*
Numbo is open source in:
https://github.com/Edditoria/numbo

under MIT license:
https://github.com/Edditoria/numbo/blob/master/LICENSE
 */

(function() {
  var Numbo, numbo;

  Numbo = (function() {
    var convert_enUS, tools;

    function Numbo() {}

    tools = {
      trimWhitespace: function(str) {
        return str.replace(/^\s+|\s+$/g, '');
      },
      parse99: function(arr1, arr10, separator) {
        var i, lenArr1, num, results;
        if (separator == null) {
          separator = ' ';
        }
        lenArr1 = arr1.length;
        results = [];
        for (num = i = 0; i <= 99; num = ++i) {
          if (num < lenArr1) {
            results.push(arr1[num]);
          } else if (num % 10 === 0) {
            results.push(arr10[Math.floor(num / 10)]);
          } else {
            results.push(arr10[Math.floor(num / 10)] + separator + arr1[num % 10].toLowerCase());
          }
        }
        return results;
      },
      check: function(input, characters) {
        if (characters == null) {
          characters = '';
        }
      },
      normalize: function(input, characters) {
        var dotIndex, inputArr, output, regexHead, regexTail;
        if (characters == null) {
          characters = '';
        }
        if (typeof input !== 'string') {
          input = input.toString();
        }
        regexHead = /,|^[$|\-]*(0|,)*(?!\.)/g;
        regexTail = /0*$/g;
        dotIndex = input.indexOf('.');
        if (dotIndex === -1) {
          output = input.replace(regexHead, '');
        } else {
          inputArr = tools.splitNum(input);
          inputArr[0] = inputArr[0].replace(regexHead, '');
          inputArr[1] = inputArr[1].replace(regexTail, '');
          output = inputArr.join('.');
        }
        if (output.indexOf('.') === 0) {
          output = '0' + output;
        }
        if (output === '') {
          output = '0';
        }
        return output;
      },
      splitNum: function(input) {
        var output;
        if (typeof input !== 'string') {
          input = input.toString();
        }
        if (input.indexOf('.') === -1) {
          output = [input, ''];
        } else {
          output = input.split('.');
        }
        if (output[0] === '') {
          output[0] = '0';
        }
        return output;
      },
      splitInt: function(int, digit) {
        var intTail, len, output, times;
        if (digit == null) {
          digit = 3;
        }
        if (typeof int !== 'string') {
          int = int.toString();
        }
        output = [];
        times = Math.ceil(int.length / digit);
        while (times) {
          len = int.length;
          intTail = int.substring(len - digit, len);
          int = int.substring(0, len - digit);
          output.unshift(intTail);
          times--;
        }
        return output;
      }
    };

    Numbo.prototype.tools = {
      trimWhitespace: tools.trimWhitespace,
      parse99: tools.parse99,
      normalize: tools.normalize,
      normalise: tools.normalize,
      splitNum: tools.splitNum,
      splitInt: tools.splitInt
    };

    convert_enUS = function(input) {
      var n1, n10, n1000, n1withZero, n99, speak999, speakDec, speakInt, speakNum;
      n1 = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
      n1withZero = ['Zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
      n10 = ['', 'Ten', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
      n1000 = ['', 'Thousand', 'Million', 'Billion', 'Trillion', 'Quadrillion', 'Quintillion', 'Sextillion', 'Septillion', 'Octillion', 'Nonillion', 'Decillion', 'Undecillion', 'Duodecillion', 'Tredecillion', 'Quattuordecillion', 'Quindecillion', 'Sexdecillion', 'Septendecillion', 'Octodecillion', 'Novemdecillion', 'Vigintillion'];
      n99 = tools.parse99(n1, n10, '-');
      speak999 = function(num, addAnd) {
        var d100, hundred, output;
        if (addAnd == null) {
          addAnd = true;
        }
        if (num <= 99) {
          return n99[num];
        } else if (num % 100 === 0) {
          return n1[Math.floor(num / 100)] + ' Hundred';
        } else {
          d100 = Math.floor(num / 100);
          hundred = addAnd ? ' Hundred and ' : ' Hundred ';
          return output = n1[d100] + hundred + n99[num % 100];
        }
      };
      speakInt = function(numArr) {
        var i, item, len1, num, output, times, unit;
        output = [];
        times = numArr.length;
        for (num = i = 0, len1 = numArr.length; i < len1; num = ++i) {
          item = numArr[num];
          times--;
          if (item !== '000') {
            unit = ' ' + n1000[times];
            item = speak999(parseInt(item, 10));
            output.push(item + unit);
          }
        }
        return output.join(' ').replace(/^\s+|\s+$/g, '');
      };
      speakDec = function(str) {
        var item, strArr;
        if (str === '') {
          return '';
        } else {
          strArr = (function() {
            var i, len1, results;
            results = [];
            for (i = 0, len1 = str.length; i < len1; i++) {
              item = str[i];
              results.push(n1withZero[parseInt(item, 10)]);
            }
            return results;
          })();
          return ' point ' + strArr.join(' ');
        }
      };
      speakNum = function(str) {
        var dec, int, intArr, strSplited;
        if (str === '0') {
          return 'zero';
        } else if (str === '1') {
          return 'one';
        } else {
          strSplited = tools.splitNum(str);
          intArr = tools.splitInt(strSplited[0]);
          int = speakInt(intArr);
          if (int === '') {
            int = 'zero';
          }
          dec = speakDec(strSplited[1]);
          return int + dec;
        }
      };
      if (input === '') {
        return null;
      } else if (input === '1e+100') {
        return 'Ding! One Google... Oops... One Googol!!';
      } else {
        if (typeof input !== 'string') {
          input = input.toString();
        }
        input = tools.normalize(input);
        return speakNum(input).toLowerCase();
      }
    };

    Numbo.prototype.enUS = convert_enUS;

    Numbo.prototype.convert = function(num, options) {
      if (options == null) {
        options = 'enUS';
      }
      return this[options](num);
    };

    return Numbo;

  })();

  numbo = new Numbo();

  if ((typeof module !== "undefined" && module !== null) && module.exports) {
    module.exports = numbo;
  }

  if (typeof window !== "undefined" && window !== null) {
    window.numbo = numbo;
  }

}).call(this);
