title: numbo
description: number-to-text javascript library
email: edditoria@gmail.com

theme: jekyll-theme-slate
show_downloads: false

host: 0.0.0.0

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

gems:
  - jekyll-coffeescript

# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
#
# # Build settings
# markdown: kramdown
# theme: minima
# gems:
#   - jekyll-feed
