title: numbo
tagline: number-to-text javascript library
description: numbo is a Javascript library. It converts number and monetary amount to written text in multiple languages. Also helpful for writing cheques (checks). Available in npm and bower. Open-source in Github.

# my seo tags (not jekyll-seo-tag)
author: Edditoria
email: edditoria@gmail.com
twitter:
  username: Edditoria
  type: summary
  image:
    url: /assets/images/numbo-web-screenshot-896x480.png
    width: 896
    height: 480
facebook:
  publisher: 100003271324063
  admins: 100003271324063
  image:
    url: /assets/images/numbo-web-screenshot-1200x630.png
    width: 1200
    height: 630
webmaster_verifications:
  google: Siv0JaYz_VzZV-ohqkY_mCHb9-4nG51qW-v4428xsIs
social:
  links:
    - https://twitter.com/edditoria
    - https://www.facebook.com/edditoria
    - https://plus.google.com/+edditoria
    - https://github.com/edditoria

theme: jekyll-theme-slate
show_downloads: false

baseurl: /numbo # for hosting in Github Pages
host: 0.0.0.0

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

gems:
  - jekyll-coffeescript
  # - jekyll-seo-tag

# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
#
# # Build settings
# markdown: kramdown
# theme: minima
# gems:
#   - jekyll-feed
