# Welcome to Jekyll!

title: numbo
tagline: number-to-text javascript library
description: Numbo is a Javascript library to convert number and monetary amount to written text in multiple languages. Also helpful for writing cheques (checks). Available in npm and bower. Open-source in Github.

# my seo tags (not jekyll-seo-tag)
author: Edditoria
email: edditoria@gmail.com
twitter:
  username: Edditoria
  type: summary
  image:
    url: /assets/images/numbo-web-screenshot-896x480.png
    width: 896
    height: 480
facebook:
  publisher: 100003271324063
  admins: 100003271324063
  image:
    url: /assets/images/numbo-web-screenshot-1200x630.png
    width: 1200
    height: 630
webmaster_verifications:
  google: Siv0JaYz_VzZV-ohqkY_mCHb9-4nG51qW-v4428xsIs
social:
  links:
    - https://twitter.com/edditoria
    - https://www.facebook.com/edditoria
    - https://plus.google.com/+edditoria
    - https://github.com/edditoria

markdown: kramdown
theme: jekyll-theme-slate
show_downloads: false

baseurl: /numbo # for hosting in Github Pages
host: 0.0.0.0

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-coffeescript
  # - jekyll-seo-tag

# defaults in github-pages gem:
# =============================

# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing
# The following items will not be processed, by default.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
